### ISSUE TITLE
Compile error in AFNetworking

### ISSUE THREAD

**Issue by yichuan1118** [contentful-labs/ContentfulWatchKitExample#1]
Having the following build error:

ContentfulWatchKitExample/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:117:21: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

XCode 6.2 6C131e

**Comment by neonichu** [comment]
I'm in the process of updating this project, but pushed my latest changes now. A workaround for this has been done in e52a0e52ea644b5d4f0266ac6004d445267de743
